@DotNet8.Architecture_CleanArchitecture.Presentation_HostAddress = http://localhost:5082

GET {{DotNet8.Architecture_CleanArchitecture.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
